[[members]]
name = "石水 泰樹"
picture = ""
description = ""

[[members]]
name = "磯部 宏征"
picture = ""
description = ""

[[members]]
name = "稲葉 昂希"
picture = ""
description = ""

[[members]]
name = "河村 綾太"
picture = ""
description = ""

[[members]]
name = "小林 悠太"
picture = ""
description = ""

[[members]]
name = "酒徳 波和"
picture = ""
description = ""

[[members]]
name = "作田 淳弥"
picture = ""
description = ""

[[members]]
name = "白井 夢月"
picture = ""
description = ""

[[members]]
name = "高木 彩花"
picture = ""
description = ""

[[members]]
name = "田中 嵩士"
picture = ""
description = "お調子者かと思いきや意外にしっかりとした一面も…？
成長著しいディアボラー！"

[[members]]
name = "戸板 治紀"
picture = ""
description = ""

[[members]]
name = "戸塚 大貴"
picture = ""
description = ""

[[members]]
name = "西村 希望"
picture = ""
description = ""

[[members]]
name = "松巾 拓未"
picture = ""
description = ""

[[members]]
name = "矢矧 春菜"
picture = ""
description = ""

[[members]]
name = "山崎 琉央"
picture = ""
description = ""

[[members]]
name = "山下 巧"
picture = ""
description = ""

[[members]]
name = "山下 湧志朗"
picture = ""
description = ""

[[members]]
name = "山田 隆太郎"
picture = ""
description = ""

[[members]]
name = "山田 隆太郎"
picture = ""
description = ""

[[members]]
name = "和田 岳"
picture = ""
description = ""

